
CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE address
ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_address_location 
ON address USING GIST (ST_MakePoint(longitude, latitude));

